[ftp]
crash_reports = "atmosphere/crash_reports"
runtime = "botwsavs"

# Mod files
[[ftp.file]]
local = "build-DDEBUG/botwsavs.nso"
target = "atmosphere/contents/01007EF00011E000/exefs/subsdk9"

[[ftp.file]]
local = "build-DDEBUG/app.npdm"
target = "atmosphere/contents/01007EF00011E000/exefs/main.npdm"

[[ftp.file]]
local = "build-DDEBUG/8E9978D50BDD20B4C8395A106C27FFDE.ips"
target = "atmosphere/exefs_patches/botwsavs/8E9978D50BDD20B4C8395A106C27FFDE.ips"

[ips]
mod_offset = "0x3483000" # this is used for address conversion for branching

[ips.main160]
id = "8E9978D50BDD20B4C8395A106C27FFDE"
offset = "0"

# Runtime placeholder/version files
[[ftp.file]]
local = "build-DDEBUG/DebugVersion.txt"
target = "botwsavs/main.log"

[[ftp.file]]
local = "build-DDEBUG/DebugVersion.txt"
target = "botwsavs/latest.txt"

[[ftp.file]]
local = "build-DDEBUG/DebugVersion.txt"
target = "atmosphere/contents/01007EF00011E000/romfs/System/Version.txt"